config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  resources :factories do
    member do
      patch :upgrade_level
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/copper_factory.rb
class CopperFactory < Factory
  PRODUCTION = {
    one: 3,
    two: 7,
    three: 14,
    four: 30,
    five: 60
  }

  UPGRADE_DURATION = {
    one: 15,
    two: 30,
    three: 60,
    four: 90
  }

  UPGRADE_COST = {
    one: { iron: 200, copper: 70, gold: 0 },
    two: { iron: 400, copper: 150, gold: 0 },
    three: { iron: 800, copper: 300, gold: 0 },
    four: { iron: 1600, copper: 600, gold: 0 }
  }
end

app/models/factory.rb
class Factory < ApplicationRecord
  # to avoid self.send("upgraded_to_level_#{level_symbol(self.level).to_s}_at"
  LEVEL_TIMESTAMP_MAPPING = {
    one: :created_at,
    two: :upgraded_to_level_two_at,
    three: :upgraded_to_level_three_at,
    four: :upgraded_to_level_four_at,
    five: :upgraded_to_level_five_at
  }

  belongs_to :user

  def production(for_level)
    self.type.constantize::PRODUCTION[Factory.level_symbol(for_level)]
  end

  def next_upgrade_duration(for_level)
    self.type.constantize::UPGRADE_DURATION[Factory.level_symbol(for_level)]
  end

  def upgrade_cost(for_level)
    self.type.constantize::UPGRADE_COST[Factory.level_symbol(for_level)]
  end

  def produced_so_far
    if self.level == 1
      produced_between(self.created_at, Time.now, 1)
    elsif self.level == 2
      [
        produced_between(self.created_at, self.send(LEVEL_TIMESTAMP_MAPPING[:two]), 1),
        produced_between(send(LEVEL_TIMESTAMP_MAPPING[:two]), Time.now, 2)
      ].reduce(&:+)
    else
      [
        produced_between(self.created_at, self.send(LEVEL_TIMESTAMP_MAPPING[:two]), 1),
        produced_between(send(LEVEL_TIMESTAMP_MAPPING[Factory.level_symbol(self.level)]), Time.now, self.level),
        (2..self.level-1).to_a.map{ |i|
          produced_between(
            send(LEVEL_TIMESTAMP_MAPPING[Factory.level_symbol(i)]),
            send(LEVEL_TIMESTAMP_MAPPING[Factory.level_symbol(i+1)]),
            i
          )
        }.reduce(&:+)
      ].reduce(&:+)
    end
  end

  def can_be_upgraded?
    self.level < 5 && DateTime.now.after?(send(Factory::LEVEL_TIMESTAMP_MAPPING[Factory.level_symbol(self.level)])) && user.has_enough_resources?(upgrade_cost(self.level + 1))
  end

  private

  def total_upgrades_cost

  end

  def produced_between(earlier_timestamp, later_timestamp, level)
    (later_timestamp.to_i - earlier_timestamp.to_i) * production(level)
  end

  def self.level_symbol(for_level)
    case for_level
    when 1
      :one
    when 2
      :two
    when 3
      :three
    when 4
      :four
    when 5
      :five
    else
      :one
    end
  end
end

app/models/gold_factory.rb
class GoldFactory < Factory
  PRODUCTION = {
    one: 2,
    two: 3,
    three: 4,
    four: 6,
    five: 8
  }

  UPGRADE_DURATION = {
    one: 15,
    two: 30,
    three: 60,
    four: 90
  }

  UPGRADE_COST = {
    one: { iron: 0, copper: 100, gold: 2 },
    two: { iron: 0, copper: 200, gold: 4 },
    three: { iron: 0, copper: 400, gold: 8 },
    four: { iron: 0, copper: 800, gold: 16 }
  }
end

app/models/iron_factory.rb
class IronFactory < Factory
  PRODUCTION = {
    one: 10,
    two: 20,
    three: 40,
    four: 80,
    five: 150
  }

  UPGRADE_DURATION = {
    one: 15,
    two: 30,
    three: 60,
    four: 90
  }

  UPGRADE_COST = {
    one: { iron: 300, copper: 100, gold: 1 },
    two: { iron: 800, copper: 250, gold: 2 },
    three: { iron: 1600, copper: 500, gold: 4 },
    four: { iron: 3000, copper: 1000, gold: 8 }
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :factories, dependent: :delete_all

  validates :username, presence: true, uniqueness: {case_sensitive: false}

  after_create :create_factories

  # TODO need to subtract resources spent on upgrades
  def resources
    {
      iron: iron_factory.produced_so_far,
      copper: copper_factory.produced_so_far,
      gold: gold_factory.produced_so_far
    }
  end

  def iron_factory
    @iron_factory ||= factories.where(type: "IronFactory").first
  end

  def copper_factory
    @copper_factory ||= factories.where(type: "CopperFactory").first
  end

  def gold_factory
    @gold_factory ||= factories.where(type: "GoldFactory").first
  end

  def has_enough_resources?(resource_request)
    self.resources[:iron] >= resource_request[:iron] &&
    self.resources[:copper] >= resource_request[:copper] &&
    self.resources[:gold] >= resource_request[:gold]
  end

  private

  def create_factories
    [IronFactory, CopperFactory, GoldFactory].each do |factory|
      factory.create(user: self)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :current_password)}
  end
end

app/controllers/factories_controller.rb
class FactoriesController < ApplicationController
  def show
    factory
  end

  def upgrade_level
    if factory.can_be_upgraded?
      new_level = factory.level + 1
      factory.update_attribute(:level, new_level)
      factory.update_attribute(Factory::LEVEL_TIMESTAMP_MAPPING[Factory.level_symbol(new_level)], DateTime.now + factory.next_upgrade_duration(factory.level).seconds)
    end
  end

  private

  def factory
    @factory ||= current_user.factories.find_by(id: params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/users/devise_controller.rb
class Users::DeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/factories/show.html.erb
<% if @factory %>
  Your magnificent Factory!
  <br>

  <%= "Type: #{@factory.type}" %>
  <br>
  <%= "Level: #{@factory.level}" %>
  <br>
  <%= "Production: #{@factory.production(@factory.level)}" %>
  <br>
  <%= "Next upgrade duration: #{@factory.next_upgrade_duration(@factory.level)}" %>
  <br>
  <%= "Next upgrade cost: #{@factory.upgrade_cost(@factory.level)}" %>
  <br>
  <% if @factory.level < 5 %>
    <%= link_to "Upgrade Level", upgrade_level_factory_path(@factory.id), data: { 'turbo-method': :patch } %>
  <% end %>
<% else %>
  Oops there seems to be nothing here!
<% end %>

app/views/home/index.html.erb
Welcome home!

<br>
<br>
Your Factories:

<br>
<%= link_to 'Iron Factory', factory_path(current_user.iron_factory.id) %>
<br>
<%= link_to 'Copper Factory', factory_path(current_user.copper_factory.id) %>
<br>
<%= link_to 'Gold Factory', factory_path(current_user.gold_factory.id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ogame2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p>
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.username %></strong>.<br>
        <%= link_to 'Home', root_path %> |
        <%= link_to 'Edit profile', edit_user_registration_path %> |
        <%= link_to "Logout", destroy_user_session_path, data: { 'turbo-method': :delete } %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path  %> |
        <%= link_to "Login", new_user_session_path  %>
      <% end %>
    </p>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <% if user_signed_in? %>
      <%= "My resources: #{current_user.resources}" %>
      <br>
    <% end %>

    <%= yield %>
  </body>
</html>